#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define DEVICE_ID "stackchan-001"
#define DEVICE_TOKEN "replace-me"

// Generated by deploy-from-relay.ps1. It is kept separate so a new Relay
// address never overwrites Wi-Fi credentials or the device token.
#include "relay_endpoint.hpp"
